# Generated by Django 5.2.7 on 2025-10-20 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleFitUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('fit_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('average_stress', models.FloatField()),
                ('max_stress', models.FloatField()),
                ('min_stress', models.FloatField()),
                ('stress_trend', models.CharField(choices=[('IMPROVING', 'Improving'), ('STABLE', 'Stable'), ('WORSENING', 'Worsening'), ('FLUCTUATING', 'Fluctuating')], max_length=20)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StressData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('heart_rate', models.FloatField(help_text='Heart rate in BPM')),
                ('heart_rate_confidence', models.FloatField(default=0.0)),
                ('sleep_duration', models.FloatField(blank=True, help_text='Sleep duration in hours', null=True)),
                ('sleep_quality', models.CharField(blank=True, choices=[('DEEP', 'Deep Sleep'), ('LIGHT', 'Light Sleep'), ('REM', 'REM Sleep'), ('AWAKE', 'Awake')], max_length=20, null=True)),
                ('steps', models.IntegerField(default=0)),
                ('calories', models.FloatField(default=0.0)),
                ('activity_duration', models.FloatField(default=0.0, help_text='Activity duration in minutes')),
                ('stress_level', models.FloatField(help_text='Calculated stress level (0-100)')),
                ('stress_category', models.CharField(choices=[('LOW', 'Low Stress'), ('MODERATE', 'Moderate Stress'), ('HIGH', 'High Stress'), ('VERY_HIGH', 'Very High Stress')], max_length=20)),
                ('hrv', models.FloatField(blank=True, help_text='Heart Rate Variability', null=True)),
                ('resting_heart_rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='stress_anal_user_id_80bc38_idx')],
            },
        ),
    ]
