# Generated by Django 3.2.25 on 2025-10-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20251019_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='messages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
